### ISSUE TITLE
Error generating the amplicons

### ISSUE THREAD

**Issue by mariaelf97** [rki-mf1/amplisim#16]
Hello!

I am trying to use AmpliSIM as following but it gives an error "Error generating the amplicons." without any explanation of the issue.

`./amplisim ~/ref_seqs/NC_045512_Hu-1.fasta ~/ref_seqs/nCoV-2019_v1.bed > amplicons.fasta`

I tried both Conda and install from source version but they both error out.

Could you help me with this?
 amplisim version is 0.2.1
Here is head of both files!
```
MN908947.3      30      54      nCoV-2019_1_LEFT        60      +
MN908947.3      385     410     nCoV-2019_1_RIGHT       60      -
MN908947.3      320     342     nCoV-2019_2_LEFT        60      +
MN908947.3      704     726     nCoV-2019_2_RIGHT       60      -
MN908947.3      642     664     nCoV-2019_3_LEFT        60      +
MN908947.3      1004    1028    nCoV-2019_3_RIGHT       60      -
MN908947.3      943     965     nCoV-2019_4_LEFT        60      +
MN908947.3      1312    1337    nCoV-2019_4_RIGHT       60      -

```

```
>NC_045512.2 Severe acute respiratory syndrome coronavirus 2 isolate Wuhan-Hu-1, complete genome
ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATCTGTTCTCTAAA
CGAACTTTAAAATCTGTGTGGCTGTCACTCGGCTGCATGCTTAGTGCACTCACGCAGTATAATTAATAAC
TAATTACTGTCGTTGACAGGACACGAGTAACTCGTCTATCTTCTGCAGGCTGCTTACGGTTTCGTCCGTG
TTGCAGCCGATCATCAGCACATCTAGGTTTCGTCCGGGTGTGACCGAAAGGTAAGATGGAGAGCCTTGTC
CCTGGTTTCAACGAGAAAACACACGTCCAACTCAGTTTGCCTGTTTTACAGGTTCGCGACGTGCTCGTAC
GTGGCTTTGGAGACTCCGTGGAGGAGGTCTTATCAGAGGCACGTCAACATCTTAAAGATGGCACTTGTGG
CTTAGTAGAAGTTGAAAAAGGCGTTTTGCCTCAACTTGAACAGCCCTATGTGTTCATCAAACGTTCGGAT
GCTCGAACTGCACCTCATGGTCATGTTATGGTTGAGCTGGTAGCAGAACTCGAAGGCATTCAGTACGGTC
GTAGTGGTGAGACACTTGGTGTCCTTGTCCCTCATGTGGGCGAAATACCAGTGGCTTACCGCAAGGTTCT
TCTTCGTAAGAACGGTAATAAAGGAGCTGGTGGCCATAGTTACGGCGCCGATCTAAAGTCATTTGACTTA
GGCGACGAGCTTGGCACTGATCCTTATGAAGATTTTCAAGAAAACTGGAACACTAAACATAGCAGTGGTG
TTACCCGTGAACTCATGCGTGAGCTTAACGGAGGGGCATACACTCGCTATGTCGATAACAACTTCTGTGG
CCCTGATGGCTACCCTCTTGAGTGCATTAAAGACCTTCTAGCACGTGCTGGTAAAGCTTCATGCACTTTG
TCCGAACAACTGGACTTTATTGACACTAAGAGGGGTGTATACTGCTGCCGTGAACATGAGCATGAAATTG
CTTGGTACACGGAACGTTCTGAAAAGAGCTATGAATTGCAGAC
```

I tried changing chromosome name to an identical name and this is what I got

```
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
Segmentation fault (core dumped)
```

**Comment by Krannich479** [comment]
Hello @mariaelf97,
thanks for using _amplisim_ and writing this very detailed issue report! First off, I would like to stress that this software is active work in progress and therefor might lacks some sanity checks yet. This will likely improve soon. 🛠️ 

1. **Your cause of error**
I looked into your commands and data and I was convinced you did everything right. Then, I tried running _amplisim_ on your provided data and had a segmentation fault myself. I figured out the reason it doesn't work is a tiny but common error: your provided primer file (BED file) uses spaces to instead to actual tabs (`\t` character). Hence, the BED file parser cannot identify the fields.

2. **Solution**
In your BED file, simply replace all the (multi-)whitespaces with an actual tab `\t`. For instance, if you use VS Code as your text editor, your can inspect the delimiter if you activate View▶️Appearance▶️Render Whitespace. After the replacement it simply works with `amplisim NC_045512_Hu-1.fasta nCoV-2019_v1.bed > amplicons.fasta`

3. **Please mind:**
The chromosome identifier of the given reference sequence does indeed have to match the chromosome identifier in the BED file. Otherwise the program does not know which sequence (chromosome) to generate the amplicons from; since there could be multiple sequences in your reference file. In your case, as you mentioned, it's probably the easiest to rename your reference sequence (inside the _fasta_ file) to `>MN908947.3`. Afterwards you need to generate the fasta index again via `samtools faidx NC_045512_Hu-1.fasta`. This was probably the cause of your segmentation fault. Finally, make sure your last primer's index is smaller than the genome size. Since `MN908947.3 != NC_045512.2` it's better to double-check.

Let me know if this solves the problem on your side. This issue ticket is helpful for me to make the software more robust!

**Comment by mariaelf97** [comment]
Thank you for your response.

I was wondering if the primer coordinates will be used in the process of creating amplicons and simulating reads?
I am asking this because the primer coordinates are according to the reference genome whereas the file that is being passed is not a reference genome.

If you use the primer sequences though, it shouldn't make a difference.

**Comment by Krannich479** [comment]
At this point, the **amplicons are generated using the chromosome name and primer coordinates**, i.e. it is purely genome index-based. Renaming your reference haplotype (inside FASTA) or the chromosome names (inside BED) is currently the only way to prepare your data for amplisim. In your case, the amplicons might be slightly off target since your reference is not what the BED file corresponds to. For very similar strains/haplotypes I expect this to still work well though.

This being said, I already though about an option for a more biologically realistic primer mapping using the primer sequence. However, I believe this is not as trivial as it may seems. It'd require some sort of alignment strategy and ideally a confidence score or binding affinity according to the alignment. I am making no promises that this will be implemented anytime soon.

**Comment by mariaelf97** [comment]
Thank you for your response.

Yes, if everything is based on coordinates in the primer file, it is not realistic because the purpose of amplicon sequencing is to study strains other than the reference strain.

Best of luck with your tool and have a nice day!
